### ISSUE TITLE
Sidebar render issue in chrome

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#95]
When opening a new tab in chrome and loading https://okfn.de the sidebar is sliding away sneakily. Other browsers seem to be fine. It's also fine on reload.

![chrome-okf-sidebar-bug](https://user-images.githubusercontent.com/78356/33443498-0632a60a-d5f8-11e7-8b5f-f23dd6644584.gif)

**Comment by stefanw** [comment]
Maybe @ffalt knows?

**Comment by ffalt** [comment]
hard to reproduce, since it's only visible after cache cleaning in my chrome. but at the very first start it's visible. my guess it's a race condition when and how chrome applies css properties. the sidebar *should* be invisible at start, but seems like the animation property is used first, so [div is visible without css] => [div gets animation property] => [div gets visibilty=false property] which leads to this black ghost animation.
I now extracted the animation properties into an .active class, which gets set by the sidebar javascript.
ugly workaround, but changing order of properties, using different properties and such did not get rid of it.
sort of the same is happening with the appearing header, I guess.

**Comment by ffalt** [comment]
meh, did not work as intended. the sidebar stayed hidden. I think now it's properly worked around.
